project:
  type: r3-theme
  # pre-render: bash _build-slides.sh
  # resources:
  #   - slides/*.html

book:
  title: "Reproducible Research in R: ISE"
  subtitle: "An introductory course on using R for reproducible research in server environments"
  author:
   - Luke W. Johnston
   - Daniel Ibsen
   - Alisa D. Kjaergaard
   - Kris Beicher
   - Omar Silverman
  date: last-modified
  repo-url: https://github.com/rostools/r-cubed-ise
  site-url: https://r-cubed-ise.rostools.org
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/syllabus.qmd
      - preamble/schedule.qmd
      - preamble/pre-course.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/server-basics.qmd
      - sessions/databases.qmd
      - sessions/prototyping.qmd
      - sessions/optimizing.qmd
      - sessions/troubleshooting.qmd
      - sessions/what-next.qmd
  appendices:
    - appendix/social.qmd
    - appendix/project.qmd
    - appendix/for-instructors.qmd
    - LICENSE.md
    - appendix/references.qmd
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html
      - text: "Code of Conduct"
        href: "https://guides.rostools.org/conduct.html"

format:
  r3-theme-html: default

editor:
  markdown:
    wrap: 72
    canonical: true
